import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopContactBar from "./components/TopContactBar";
import MainNavBar from "./components/MainNavBar";
import Footer from "./components/Footer";

// Reminder: Run 'pnpm add react-icons' if not already installed for icon support in TopContactBar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <TopContactBar />
          <MainNavBar />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
